pid /tmp/nginx.pid;

worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection "1; mode=block";

    # gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 256;

    # Performance settings
    sendfile on;
    tcp_nopush on;

    location / {
      # Support SPAs by serving /index.html in case there's no file
      try_files $uri $uri/ /index.html;
    }

    location /favicon.ico {
      # Do not serve /index.html for /favicon.ico
      try_files $uri =404;
    }

    # Deny access to hidden files
    location ~ /\. {
      deny all;
    }

    # Allow versioned files to be cached indefinitely
    location ~* \.v- {
      expires 1y;
      access_log off;
      add_header Cache-Control "public, immutable";
    }
  }
}
